/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/roots/tabs/explore` | `/roots/tabs/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/roots/tabs/profile` | `/roots/tabs/profile`; params?: Router.UnknownInputParams; } | { pathname: `/roots/tabs/explore`; params?: Router.UnknownInputParams; } | { pathname: `/roots/tabs`; params?: Router.UnknownInputParams; } | { pathname: `/roots/tabs/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/roots/properties/[id]` | `/roots/properties/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/roots/properties/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/roots/tabs/explore` | `/roots/tabs/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/roots/tabs/profile` | `/roots/tabs/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/roots/tabs/explore`; params?: Router.UnknownOutputParams; } | { pathname: `/roots/tabs`; params?: Router.UnknownOutputParams; } | { pathname: `/roots/tabs/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/roots/properties/[id]` | `/roots/properties/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/roots/properties/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/sign-in${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/roots/tabs/explore${`?${string}` | `#${string}` | ''}` | `/roots/tabs/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/roots/tabs/profile${`?${string}` | `#${string}` | ''}` | `/roots/tabs/profile${`?${string}` | `#${string}` | ''}` | `/roots/tabs/explore${`?${string}` | `#${string}` | ''}` | `/roots/tabs${`?${string}` | `#${string}` | ''}` | `/roots/tabs/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/roots/tabs/explore` | `/roots/tabs/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/roots/tabs/profile` | `/roots/tabs/profile`; params?: Router.UnknownInputParams; } | { pathname: `/roots/tabs/explore`; params?: Router.UnknownInputParams; } | { pathname: `/roots/tabs`; params?: Router.UnknownInputParams; } | { pathname: `/roots/tabs/profile`; params?: Router.UnknownInputParams; } | `${'/(tabs)'}/roots/properties/${Router.SingleRoutePart<T>}` | `/roots/properties/${Router.SingleRoutePart<T>}` | `/roots/properties/${Router.SingleRoutePart<T>}` | { pathname: `${'/(tabs)'}/roots/properties/[id]` | `/roots/properties/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/roots/properties/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
